[package]
name = "groq-chat-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.10"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.64"
serde_derive = "1.0.117"